# Site settings
title: Zetta AI
email: contact@zetta.ai
url: https://zettaai.github.io
description: "The ultimate brain maps:<br><br>neuronal wiring diagrams at synaptic resolution"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Zetta AI

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/@zettabrain
  - title: github
    url: https://github.com/zettaai

# Build settings
markdown: kramdown
permalink: pretty
